<?php
/**
 * @file
 * behatrunner module implementation
 */

/**
 * Implements hook_entity_info().
 */
function behatrunner_entity_info() {
  return array(
    'behatrunner_scenario' => array(
      'label' => t('Behat Runner Scenario'),
      'entity class' => 'BehatRunnerScenario',
      'controller class' => 'BehatRunnerScenarioController',
      'base table' => 'behatrunner_scenario',
      'uri callback' => 'behatrunner_scenario_uri',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'bsid',
      ),
      'static cache' => TRUE,
      'module' => 'behatrunner_scenario',
      'views controller class' => 'EntityDefaultViewsController',
    ),
  );
}

/**
 * Implements hook_entity_property_info().
 */
function behatrunner_entity_property_info() {
  $info = array();
  $properties = &$info['behatrunner_scenario']['properties'];

  $properties['bsid'] = array(
    'label' => 'Behat Runner Scenario ID',
    'description' => t('The unique ID for the behatrunner_test_location.'),
    'type' => 'integer',
    'schema field' => 'bsid',
  );
  $properties['title'] = array(
    'label' => 'title',
    'description' => t('The human-readable title of this scenario.'),
    'type' => 'varchar',
    'schema field' => 'title',
  );
  $properties['location'] = array(
    'label' => 'Location',
    'description' => t('The location of the scenario, relative to the Drupal base, in the form of path/to/filename:line-number'),
    'type' => 'varchar',
    'schema field' => 'location',
  );
  $properties['module'] = array(
    'label' => 'Module',
    'description' => t('The module to which this scenario belongs.'),
    'type' => 'varchar',
    'schema field' => 'module',
  );
}

/**
 * Implements hook_permission().
 */
function behatrunner_permission() {
  $permissions = array(
    'create behat scenario entities' => array(
      'title' => t('Create behat scenario'),
      'description' => t('Allows users to create behat scenario.'),
      'restrict access' => TRUE,
    ),
    'view behat scenario entities' => array(
      'title' => t('View behat scenario'),
      'description' => t('Allows users to view behat scenario.'),
      'restrict access' => TRUE,
    ),
  );
  return $permissions;
}


/**
 * Access callback.
 */
function behatrunner_test_location_access($op, $projectqa_phploc_result, $account = NULL, $entity_type = NULL) {
  global $user;
  if (!isset($account)) {
    $account = $user;
  }
  switch ($op) {
    case 'create':
      return user_access('administer behatrunner_test_location entities', $account)
          || user_access('create behatrunner_test_location entities', $account);
    case 'view':
      return user_access('administer behatrunner_test_location entities', $account)
          || user_access('view behatrunner_test_location entities', $account);
  }
}
